Inside Stopper_ex.PY 


('690', '1')
Project id is :690
100,5765,2284,7830,8605,8935,9174,9279,9356,9880
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 100
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 5765
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 2284
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 7830
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 8605
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 8935
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 9174
Exception caught in th-controllor--psutil.NoSuchProcess no process found with pid 9279
psutil.Process(pid=9356, name='python')
Parent Process already KIlled
psutil.Process(pid=9880, name='python')
Killing Process with id -->psutil.Process(pid=10088, name='ruby')
Killed Process with id -->psutil.Process(pid=10088, name='ruby')
Parent Process already KIlled
Project id is :690
